version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/rute
    binary: rute
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "rute_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: Sandbye
      name: homebrew-rute
    homepage: https://github.com/Sandbye/rute
    description: Browse and export your API routes and Zod schemas from the terminal
    license: MIT
    install: |
      bin.install "rute"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
